name: Update badges

on:
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: evesquare/badge-readme@feature/img_size
        with:       
          CREDLY_USER: juon-kawakami
